setopt rematch_pcre            # Match regular expressions using PCRE if available
setopt hist_reduce_blanks      # Reduce whitespace from commands
setopt autopushd pushdminus pushdsilent   # Use pushd when cd-ing around
setopt hist_ignore_all_dups               # Filter non-contiguous duplicates from history
setopt no_flow_control                    # disable start (C-s) and stop (C-q) characters
setopt pushd_ignore_dups                  # don't push multiple copies of same dir onto stack
setopt auto_param_slash                   # tab completing directory appends a slash
setopt share_history                      # share history between shell processes

# - { ZStyle } ------------------------------------------------------------------------------ #
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''

# - { Keybinds } ---------------------------------------------------------------------------- #
# Use ctrl+{arrows} to jump around words
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
# Use ctrl+backspace/delete to kill words
bindkey '^H' backward-kill-word
bindkey '^[[3;5~' kill-word
# Use {arrows} with substring search
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
# Home and end
bindkey '^[[F' end-of-line
bindkey '^[[H' beginning-of-line

if tput cbt &> /dev/null; then
  bindkey "$(tput cbt)" reverse-menu-complete # make Shift-tab go to previous completion
fi

# - { List subdirectories when changing directory }------------------------------------------ #
autoload -Uz add-zsh-hook
function -auto-ls-after-cd() {
  emulate -L zsh
  [[ $ZSH_EVAL_CONTEXT == toplevel:shfunc ]] || return
  if (( $+commands[lsd] )); then lsd -d -- *(N/); else ls -d -- *(N/); fi
}
[[ $ZSH_SELF_LSPWD == true ]] && add-zsh-hook chpwd -auto-ls-after-cd