setopt rematch_pcre            # Match regular expressions using PCRE if available
setopt null_glob               # Do not report an error if a file pattern is not matched

# - { ZStyle } ------------------------------------------------------------------------------ #
autoload -U compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''

# - { Keybinds } ---------------------------------------------------------------------------- #
# Use ctrl+{arrows} to jump around words
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
# Use ctrl+backspace/delete to kill words
bindkey '^H' backward-kill-word
bindkey '^[[3;5~' kill-word
# Use {arrows} with substring search
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# -- { Shell Completions } ----------------------------------------------------------------- #

if [ $commands[kubectl] ]; then source <(kubectl completion zsh); fi
if [ $commands[flux] ]; then source <(flux completion zsh); fi
if [ $commands[helm] ]; then source <(helm completion zsh); fi

# - { List subdirectories when changing directory }------------------------------------------ #
if [ x$ZSH_SELF_LSPWD = xtrue ]; then
  # Define a function to list directories with exa and add it as a hook
  function -auto-ls-after-cd() {
    emulate -L zsh
    # Only in response to a user-initiated `cd`, not indirectly (eg. via another function).
    if [ "$ZSH_EVAL_CONTEXT" = "toplevel:shfunc" ]; then
      command -v lsd > /dev/null && lsd --directory-only * || ls
    fi
  }
  add-zsh-hook chpwd -auto-ls-after-cd
fi